name: deploy

on: 
  push:
    branches:
      - master

jobs:

  docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/docker-login@v1
        with:
          login-server: contoso.azurecr.io
          username: codfrm
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag codfrm/wxmp:latest
          docker push codfrm/wxmp:latest

